java -jar ./closure-compiler/compiler.jar \
    --language_out=ES5 \
    --formatting PRETTY_PRINT \
    --debug true \
    --js ./test/**.js \
    --js ./test/**/*.js \
    --js ./src/**.js \
    --js ./src/**/*.js \
    --js_module_root test \
    --js_module_root src \
    --js_output_file bin/jspyder.tests.js \
    --warning_level=VERBOSE